### ISSUE TITLE
User multi-login does not work when running BOCA with a reverse proxy

### ISSUE THREAD

**Issue by rlaiola** [cassiopc/boca#18]
### What is this issue about?

Teams (users) cannot log in from different Web browsers (User Agents) when BOCA runs behind a reverse proxy (e.g., [Traefik](https://github.com/traefik/traefik)), which allows for a custom URL like inf.university.br/boca, even though the `MultiLogins` option is set to '_Yes_'.

The problem occurs because in the part of the code in which the User Agent is considered the `usermultilogin` flag is not taken into account. It's important to keep in mind that running BOCA with a reverse proxy, all User IPs will be always the same (actually, they will have the proxy's IP).

https://github.com/cassiopc/boca/blob/master/src/flog.php#L166-L189

This issue does not allow using BOCA + reverse proxy to host remote programing contests, in which even the team members are non-collocated (considering all of them would be able to log in with the same account credentials).

### How to test it?

In order to rapidly demonstrate the problem, a dockerized version of BOCA is used.

_docker-compose.yml_
````
version: '3'

services:

    traefik:
        image: "traefik:v2.6"
        container_name: "traefik"
        command:
              #- "--log.level=DEBUG"
              - "--api.insecure=true"
              - "--providers.docker=true"
              - "--providers.docker.exposedbydefault=false"
              - "--entrypoints.web.address=:80"
        ports:
              - "80:80"
              - "8080:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock:ro"

    boca-web:
        image: ghcr.io/joaofazolo/boca-docker/boca-web
        privileged: true
        restart: unless-stopped
        depends_on:
            - boca-postgres
        environment:
            # Database configuration
            - DB_HOST=boca-postgres
            - DB_PORT=5432
            - DB_NAME=bocadb
            # unprivileged boca user
            - DB_USER=bocauser
            - DB_PASSWORD=dAm0HAiC
            # privileged boca user
            - DB_SUPER_USER=bocauser
            - DB_SUPER_PASSWORD=dAm0HAiC
            # initial password that is used by the admin user (web app)
            # If not set, the default value is 'boca'
            - BOCA_PASSWORD=boca
            # secret key to be used in HTTP headers
            # MUST set it with any random large enough sequence
            - BOCA_KEY=GG56KFJtNDBGjJprR6ex
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.boca.rule=Host(`localhost`) && PathPrefix(`/boca`)"
            - "traefik.http.routers.boca.entrypoints=web"
            - "traefik.http.services.boca.loadbalancer.server.port=80"

    boca-jail:
        image: ghcr.io/joaofazolo/boca-docker/boca-jail
        privileged: true
        restart: unless-stopped
        depends_on:
            - boca-postgres
        environment:
            # Database configuration
            - DB_HOST=boca-postgres
            - DB_PORT=5432
            - DB_NAME=bocadb
            # unprivileged boca user
            - DB_USER=bocauser
            - DB_PASSWORD=dAm0HAiC
            - PASSWD=dAm0HAiC

    boca-postgres:
        image: postgres
        container_name: boca-postgres
        restart: unless-stopped
        environment:
            # Database configuration
            # privileged boca user
            POSTGRES_USER: bocauser
            POSTGRES_PASSWORD: dAm0HAiC

````

1. Open a Terminal window and make sure [Docker Desktop/CE](https://www.docker.com/get-started) is up and running;
1. Download/save the file _docker-compose.yml_ and place it in the shell current directory (_~/Downloads_ in the example). Then, run:

        docker-compose -f docker-compose.yml up -d

<img width="1076" alt="Screen Shot 2022-05-20 at 10 38 06" src="https://user-images.githubusercontent.com/4059310/169540523-3f597fd4-326b-472c-9896-319b7fa18bc6.png">

1. Open a Web browser, visit [localhost/boca](http://localhost/boca/) and log in with the credentials `Name: system | Password: boca`;
1. Click on the '_Contest_' menu (top/left) and select '_new_' in the ComboBox;
1. Leave the form as it is, click on the button '_Send_' (confirm it) and then on '_Activate_' (confirm it). You will be automatically logged out;
1. Log in with the credentials `Name: admin | Password: boca`;
1. Click on the '_Users_' menu and fill in the form with the information below (**IMPORTANT: the MultiLogins field must be set to YES**). Click on the '_Send_' button. The new user must appear in the list. After that, just log out.
```
    User Site Number: 1
    User Number: 2000
    Username: topcoder
    ICPC ID: 
    Type: Team
    Enabled: Yes
    MultiLogins (local teams should be set to No): Yes
    User Full Name: 
    User Description: 
    User IP: 
    Password: boca
    Retype Password: boca
    Allow password change: No
    Admin (this user) Password: boca
```
1. In order to reproduce the problem, it is necessary to log in using 2 different User Agents (Web browsers) using the credentials `Name: topcoder | Password: boca`;
    #### Example: First, logging in Google Chrome and then trying to do the same in Safari.
    <img width="1072" alt="Screen Shot 2022-05-20 at 07 13 58" src="https://user-images.githubusercontent.com/4059310/169537188-e090207a-ca73-44c9-9727-69b1a1cfa8c1.png">
    <img width="1072" alt="Screen Shot 2022-05-20 at 07 13 42" src="https://user-images.githubusercontent.com/4059310/169537271-3b318e45-df05-4912-959a-e796e59a94ce.png">
    <img width="1072" alt="Screen Shot 2022-05-20 at 07 14 52" src="https://user-images.githubusercontent.com/4059310/169537745-13cb708e-376d-4432-84df-61a20737099d.png">
    <img width="1072" alt="Screen Shot 2022-05-20 at 07 15 02" src="https://user-images.githubusercontent.com/4059310/169537775-eb8a9461-6766-4e3a-9f04-991e73338bde.png">
1. To stop the application (considering that the shell is in the same directory):

        docker-compose -f docker-compose.yml down
