### ISSUE TITLE
Autojudge (Jail) does not judge submissions (runs) if it is started before a contest is activated

### ISSUE THREAD

**Issue by rlaiola** [cassiopc/boca#29]
### What is this issue about?

If the autojudge is started before a contest is created and activated, it is necessary to kill the process and restart it in order to have the runs of that contest judged. The problem also happens if one creates and activates yet another contest, jail (autojudge) will not judge runs of the just activated contest until it is restarted.

The problem occurs because in the autojudge code the variable that holds the active contest is set here...

https://github.com/cassiopc/boca/blob/master/src/private/autojudging.php#L82

but it's never updated inside the infinite loop. Thus the autojudge gets stuck here...

https://github.com/cassiopc/boca/blob/master/src/private/autojudging.php#L87-L96

This seems to be an unexpected behavior (at least from a contest creator perspective) and, more importantly, it requires human intervention to make it work (that is, autojudge needs to be restarted) every single time another contest is activated. Although creating and activating different contests on the same host machine might not be a frequent use case, this imposes a caveat.

### How to test it?

In order to demonstrate the problem, a dockerized version of BOCA is used.

1. Open a Terminal window and make sure [Docker Desktop/CE](https://www.docker.com/get-started) is up and running;

    <img width="892" alt="Screen Shot 2023-04-17 at 00 11 07" src="https://user-images.githubusercontent.com/4059310/232368942-6ccedf35-d796-4cda-a3a6-87e4282b0488.png">

1. Download/save the _docker-compose.yml_ file and place it in the shell current directory (_~/Downloads_ in the example);

    _docker-compose.yml_
    ````
    version: '3.8'

    services:

        # web app
        boca-web:
            image: ghcr.io/joaofazolo/boca-docker/boca-web:1.1.0
            depends_on:
                - boca-db
            restart: unless-stopped
            environment:
                # database configuration
                # privileged user password
                - BOCA_DB_SUPER_PASSWORD=dAm0HAiC
            ports: 
                - 8000:80

        # online judge
        boca-jail:
            image: ghcr.io/joaofazolo/boca-docker/boca-jail:1.1.0
            depends_on:
                - boca-db
            restart: unless-stopped

        # database
        boca-db:
            image: postgres:14-alpine
            environment:
                # database configuration
                # privileged user password
                - POSTGRES_PASSWORD=dAm0HAiC

    ````

1. Then, run:

        docker-compose -f docker-compose.yml up -d

    <img width="892" alt="Screen Shot 2023-04-16 at 23 40 28" src="https://user-images.githubusercontent.com/4059310/232365195-8908c98d-1970-4965-a4f7-7c5c784affc6.png">

    **NOTE:** **In this example the autojudge (_downloads-boca-jail-1_) is started alongside the web service (_downloads-boca-web-1_). Therefore, `$activecontest=DBGetActiveContest();` will be set to `0` (Fake contest) as soon as autojudge is up and running (and before a new contest is created via the web interface).**

1. Open a Web browser, visit [localhost:8000/boca](http://localhost:8000/boca/) and log in with the credentials `Name: system | Password: boca`;
1. Click on the '_Contest_' menu (top/left) and select '_new_' in the ComboBox;
1. Leave the form as it is, click on the button '_Send_' (confirm it) and then on '_Activate_' (confirm it). You will be automatically logged out;

    <img width="1246" alt="Screen Shot 2023-04-16 at 23 43 44" src="https://user-images.githubusercontent.com/4059310/232365492-c35597b4-9293-42a7-a0f3-3c30eca8c1f3.png">

    **NOTE:** **The id (Contest number) of this contest is `1`, which is different from the value of the aforementioned `$activecontest` variable at the autojudge.**

1. Log in with the credentials `Name: admin | Password: boca`;
1. Click on the '_Problems_' menu and fill in the form with the information below.  Download the problem file from [here](https://github.com/cassiopc/boca/blob/master/doc/problemexamples/abacaxi.zip) and choose it in the 'Choose File' button. Click on the '_Send_' button and confirm ('OK'). The new problem must appear in the list;

    ```
    Number:	1
    Short Name (usually a letter, no spaces): abacaxi
    Problem package (ZIP): abacaxi.zip
    Color name: green
    Color (RGB HTML format): 00FF00
    ```

    <img width="1246" alt="Screen Shot 2023-04-16 at 23 46 23" src="https://user-images.githubusercontent.com/4059310/232365847-366b509f-686c-4ee0-8cf8-b08a77efcd5e.png">

1. Click on the '_Users_' menu and fill in the form with the information below. Click on the '_Send_' button and confirm ('OK'). The new user must appear in the list. After that, just log out;

    ```
    User Site Number: 1
    User Number: 2000
    Username: topcoder
    ICPC ID: 
    Type: Team
    Enabled: Yes
    MultiLogins (local teams should be set to No): No
    User Full Name: 
    User Description: 
    User IP: 
    Password: boca
    Retype Password: boca
    Allow password change: No
    Admin (this user) Password: boca
    ```

    <img width="1246" alt="Screen Shot 2023-04-16 at 23 48 09" src="https://user-images.githubusercontent.com/4059310/232366118-966b9cb7-0144-4950-a7f1-4cd411edd384.png">

1. Next, log in with the credentials `Name: topcoder | Password: boca`. Once the contest starts, click on the '_Runs_' menu and fill in the form with the information below. It doesn't really matter the source code file, just pick a file, click on the '_Send_' button and confirm ('OK'). The new run must appear in the list. After that, just log out;

    ```
    Problem: abacaxi
    Language: C
    Source code: teste.c
    ```

    <img width="1246" alt="Screen Shot 2023-04-16 at 23 54 41" src="https://user-images.githubusercontent.com/4059310/232366888-fef9cf89-e883-4136-a8dc-255fabb05604.png">

1. Log in once again with the credentials `Name: admin | Password: boca` and click on the '_Runs_' menu. Although the autojudge is up and running, it will not judge the submitted run due to the problem described above;

    <img width="1246" alt="Screen Shot 2023-04-16 at 23 56 26" src="https://user-images.githubusercontent.com/4059310/232367542-af5d6eac-72e8-462c-b168-710fc2b8ce60.png">

1.  In order to 'fix' that it is necessary to restart the autojudge. In this example, this is achieved restarting the container with the command below (change the container name accordingly):

        docker restart downloads-boca-jail-1

    <img width="892" alt="Screen Shot 2023-04-17 at 00 01 17" src="https://user-images.githubusercontent.com/4059310/232367869-604a5eca-8d35-4a23-bca3-02c5e594d82c.png">

1. Just reload the current web page (that is '_Runs_' logged in as `admin`), click on the run number and you will be able to see that it was judged by the autojudge;

    <img width="1246" alt="Screen Shot 2023-04-17 at 00 03 37" src="https://user-images.githubusercontent.com/4059310/232368059-f0740cbc-72b1-48d9-99fc-6bf724a772bf.png">

1. To stop the application (considering that the shell is in the same directory):

        docker-compose -f docker-compose.yml down
